import type { Metadata } from "next";
import { Geist, Geist_Mono, Cedarville_Cursive, Covered_By_Your_Grace } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cedarvilleCursive = Cedarville_Cursive({
  variable: "--font-cedarville-cursive",
  subsets: ["latin"],
  weight: "400",
});

const coveredByYourGrace = Covered_By_Your_Grace({
  variable: "--font-covered-by-your-grace",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Anushka ka budday",
  description: "Generated by yours truly",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cedarvilleCursive.variable} ${coveredByYourGrace.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
